package com.paperteam.industriallevel.setup;

import com.paperteam.industriallevel.block.CoalPowerGeneratorBlockEntity;
import com.paperteam.industriallevel.block.*;
import com.paperteam.industriallevel.item.*;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraftforge.common.extensions.IForgeMenuType;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import static com.paperteam.industriallevel.IndustrialLevel.ModId;

public class Registration {

    private static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, ModId);
    private static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, ModId);
    private static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITIES, ModId);
    private static final DeferredRegister<MenuType<?>> CONTAINERS = DeferredRegister.create(ForgeRegistries.CONTAINERS, ModId);

    public static void init(){
        ITEMS.register(FMLJavaModLoadingContext.get().getModEventBus());
        BLOCKS.register(FMLJavaModLoadingContext.get().getModEventBus());
        BLOCK_ENTITIES.register(FMLJavaModLoadingContext.get().getModEventBus());
        CONTAINERS.register(FMLJavaModLoadingContext.get().getModEventBus());
    }

    public static final RegistryObject<TitaniumOre> TITANIUM_ORE = BLOCKS.register("titanium_ore", TitaniumOre::new);
    public static final RegistryObject<DeepslateTitaniumOre> DEEPSLATE_TITANIUM_ORE = BLOCKS.register("deepslate_titanium_ore", DeepslateTitaniumOre::new);
    public static final RegistryObject<NetherTitaniumOre> NETHER_TITANIUM_ORE = BLOCKS.register("nether_titanium_ore", NetherTitaniumOre::new);
    public static final RegistryObject<EndTitaniumOre> END_TITANIUM_ORE = BLOCKS.register("end_titanium_ore", EndTitaniumOre::new);
    public static final RegistryObject<TitaniumBlock> TITANIUM_BLOCK = BLOCKS.register("titanium_block", TitaniumBlock::new);
    public static final RegistryObject<ChlorophyteOre> CHLOROPHYTE_ORE = BLOCKS.register("chlorophyte_ore", ChlorophyteOre::new);
    public static final RegistryObject<DeepslateChlorophyteOre> DEEPSLATE_CHLOROPHYTE_ORE = BLOCKS.register("deepslate_chlorophyte_ore", DeepslateChlorophyteOre::new);
    public static final RegistryObject<NetherChlorophyteOre> NETHER_CHLOROPHYTE_ORE = BLOCKS.register("nether_chlorophyte_ore", NetherChlorophyteOre::new);
    public static final RegistryObject<EndChlorophyteOre> END_CHLOROPHYTE_ORE = BLOCKS.register("end_chlorophyte_ore", EndChlorophyteOre::new);
    public static final RegistryObject<ChlorophyteBlock> CHLOROPHYTE_BLOCK = BLOCKS.register("chlorophyte_block", ChlorophyteBlock::new);
    public static final RegistryObject<BronzeOre> BRONZE_ORE = BLOCKS.register("bronze_ore", BronzeOre::new);
    public static final RegistryObject<DeepslateBronzeOre> DEEPSLATE_BRONZE_ORE = BLOCKS.register("deepslate_bronze_ore", DeepslateBronzeOre::new);
    public static final RegistryObject<NetherBronzeOre> NETHER_BRONZE_ORE = BLOCKS.register("nether_bronze_ore", NetherBronzeOre::new);
    public static final RegistryObject<EndBronzeOre> END_BRONZE_ORE = BLOCKS.register("end_bronze_ore", EndBronzeOre::new);
    public static final RegistryObject<BronzeBlock> BRONZE_BLOCK = BLOCKS.register("bronze_block", BronzeBlock::new);
    public static final RegistryObject<TinOre> TIN_ORE = BLOCKS.register("tin_ore", TinOre::new);
    public static final RegistryObject<DeepslateTinOre> DEEPSLATE_TIN_ORE = BLOCKS.register("deepslate_tin_ore", DeepslateTinOre::new);
    public static final RegistryObject<NetherTinOre> NETHER_TIN_ORE = BLOCKS.register("nether_tin_ore", NetherTinOre::new);
    public static final RegistryObject<EndTinOre> END_TIN_ORE = BLOCKS.register("end_tin_ore", EndTinOre::new);
    public static final RegistryObject<TinBlock> TIN_BLOCK = BLOCKS.register("tin_block", TinBlock::new);
    public static final RegistryObject<ZincOre> ZINC_ORE = BLOCKS.register("zinc_ore", ZincOre::new);
    public static final RegistryObject<DeepslateZincOre> DEEPSLATE_ZINC_ORE = BLOCKS.register("deepslate_zinc_ore", DeepslateZincOre::new);
    public static final RegistryObject<NetherZincOre> NETHER_ZINC_ORE = BLOCKS.register("nether_zinc_ore", NetherZincOre::new);
    public static final RegistryObject<EndZincOre> END_ZINC_ORE = BLOCKS.register("end_zinc_ore", EndZincOre::new);
    public static final RegistryObject<ZincBlock> ZINC_BLOCK = BLOCKS.register("zinc_block", ZincBlock::new);
    public static final RegistryObject<NickelOre> NICKEL_ORE = BLOCKS.register("nickel_ore", NickelOre::new);
    public static final RegistryObject<DeepslateNickelOre> DEEPSLATE_NICKEL_ORE = BLOCKS.register("deepslate_nickel_ore", DeepslateNickelOre::new);
    public static final RegistryObject<NetherNickelOre> NETHER_NICKEL_ORE = BLOCKS.register("nether_nickel_ore", NetherNickelOre::new);
    public static final RegistryObject<EndNickelOre> END_NICKEL_ORE = BLOCKS.register("end_nickel_ore", EndNickelOre::new);
    public static final RegistryObject<NickelBlock> NICKEL_BLOCK = BLOCKS.register("nickel_block", NickelBlock::new);
    public static final RegistryObject<LeadOre> LEAD_ORE = BLOCKS.register("lead_ore", LeadOre::new);
    public static final RegistryObject<DeepslateLeadOre> DEEPSLATE_LEAD_ORE = BLOCKS.register("deepslate_lead_ore", DeepslateLeadOre::new);
    public static final RegistryObject<NetherLeadOre> NETHER_LEAD_ORE = BLOCKS.register("nether_lead_ore", NetherLeadOre::new);
    public static final RegistryObject<EndLeadOre> END_LEAD_ORE = BLOCKS.register("end_lead_ore", EndLeadOre::new);
    public static final RegistryObject<LeadBlock> LEAD_BLOCK = BLOCKS.register("lead_block", LeadBlock::new);
    public static final RegistryObject<OsmiumOre> OSMIUM_ORE = BLOCKS.register("osmium_ore", OsmiumOre::new);
    public static final RegistryObject<DeepslateOsmiumOre> DEEPSLATE_OSMIUM_ORE = BLOCKS.register("deepslate_osmium_ore", DeepslateOsmiumOre::new);
    public static final RegistryObject<NetherOsmiumOre> NETHER_OSMIUM_ORE = BLOCKS.register("nether_osmium_ore", NetherOsmiumOre::new);
    public static final RegistryObject<EndOsmiumOre> END_OSMIUM_ORE = BLOCKS.register("end_osmium_ore", EndOsmiumOre::new);
    public static final RegistryObject<OsmiumBlock> OSMIUM_BLOCK = BLOCKS.register("osmium_block", OsmiumBlock::new);
    public static final RegistryObject<PlatinumOre> PLATINUM_ORE = BLOCKS.register("platinum_ore", PlatinumOre::new);
    public static final RegistryObject<DeepslatePlatinumOre> DEEPSLATE_PLATINUM_ORE = BLOCKS.register("deepslate_platinum_ore", DeepslatePlatinumOre::new);
    public static final RegistryObject<NetherPlatinumOre> NETHER_PLATINUM_ORE = BLOCKS.register("nether_platinum_ore", NetherPlatinumOre::new);
    public static final RegistryObject<EndPlatinumOre> END_PLATINUM_ORE = BLOCKS.register("end_platinum_ore", EndPlatinumOre::new);
    public static final RegistryObject<PlatinumBlock> PLATINUM_BLOCK = BLOCKS.register("platinum_block", PlatinumBlock::new);
    public static final RegistryObject<SilverOre> SILVER_ORE = BLOCKS.register("silver_ore", SilverOre::new);
    public static final RegistryObject<DeepslateSilverOre> DEEPSLATE_SILVER_ORE = BLOCKS.register("deepslate_silver_ore", DeepslateSilverOre::new);
    public static final RegistryObject<NetherSilverOre> NETHER_SILVER_ORE = BLOCKS.register("nether_silver_ore", NetherSilverOre::new);
    public static final RegistryObject<EndSilverOre> END_SILVER_ORE = BLOCKS.register("end_silver_ore", EndSilverOre::new);
    public static final RegistryObject<SilverBlock> SILVER_BLOCK = BLOCKS.register("silver_block", SilverBlock::new);
    public static final RegistryObject<UraniumOre> URANIUM_ORE = BLOCKS.register("uranium_ore", UraniumOre::new);
    public static final RegistryObject<DeepslateUraniumOre> DEEPSLATE_URANIUM_ORE = BLOCKS.register("deepslate_uranium_ore", DeepslateUraniumOre::new);
    public static final RegistryObject<NetherUraniumOre> NETHER_URANIUM_ORE = BLOCKS.register("nether_uranium_ore", NetherUraniumOre::new);
    public static final RegistryObject<EndUraniumOre> END_URANIUM_ORE = BLOCKS.register("end_uranium_ore", EndUraniumOre::new);
    public static final RegistryObject<UraniumBlock> URANIUM_BLOCK = BLOCKS.register("uranium_block", UraniumBlock::new);

    public static final RegistryObject<Item> TITANIUM_ORE_ITEM = ITEMS.register("titanium_ore", () -> new BlockItem(TITANIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_TITANIUM_ORE_ITEM = ITEMS.register("deepslate_titanium_ore", () -> new BlockItem(DEEPSLATE_TITANIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_TITANIUM_ORE_ITEM = ITEMS.register("nether_titanium_ore", () -> new BlockItem(NETHER_TITANIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_TITANIUM_ORE_ITEM = ITEMS.register("end_titanium_ore", () -> new BlockItem(END_TITANIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> TITANIUM_BLOCK_ITEM = ITEMS.register("titanium_block", () -> new BlockItem(TITANIUM_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> CHLOROPHYTE_ORE_ITEM = ITEMS.register("chlorophyte_ore", () -> new BlockItem(CHLOROPHYTE_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_CHLOROPHYTE_ORE_ITEM = ITEMS.register("deepslate_chlorophyte_ore", () -> new BlockItem(DEEPSLATE_CHLOROPHYTE_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_CHLOROPHYTE_ORE_ITEM = ITEMS.register("nether_chlorophyte_ore", () -> new BlockItem(NETHER_CHLOROPHYTE_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_CHLOROPHYTE_ORE_ITEM = ITEMS.register("end_chlorophyte_ore", () -> new BlockItem(END_CHLOROPHYTE_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> CHLOROPHYTE_BLOCK_ITEM = ITEMS.register("chlorophyte_block", () -> new BlockItem(CHLOROPHYTE_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> BRONZE_ORE_ITEM = ITEMS.register("bronze_ore", () -> new BlockItem(BRONZE_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_BRONZE_ORE_ITEM = ITEMS.register("deepslate_bronze_ore", () -> new BlockItem(DEEPSLATE_BRONZE_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_BRONZE_ORE_ITEM = ITEMS.register("nether_bronze_ore", () -> new BlockItem(NETHER_BRONZE_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_BRONZE_ORE_ITEM = ITEMS.register("end_bronze_ore", () -> new BlockItem(END_BRONZE_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> BRONZE_BLOCK_ITEM = ITEMS.register("bronze_block", () -> new BlockItem(BRONZE_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> TIN_ORE_ITEM = ITEMS.register("tin_ore", () -> new BlockItem(TIN_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_TIN_ORE_ITEM = ITEMS.register("deepslate_tin_ore", () -> new BlockItem(DEEPSLATE_TIN_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_TIN_ORE_ITEM = ITEMS.register("nether_tin_ore", () -> new BlockItem(NETHER_TIN_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_TIN_ORE_ITEM = ITEMS.register("end_tin_ore", () -> new BlockItem(END_TIN_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> TIN_BLOCK_ITEM = ITEMS.register("tin_block", () -> new BlockItem(TIN_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> ZINC_ORE_ITEM = ITEMS.register("zinc_ore", () -> new BlockItem(ZINC_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_ZINC_ORE_ITEM = ITEMS.register("deepslate_zinc_ore", () -> new BlockItem(DEEPSLATE_ZINC_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_ZINC_ORE_ITEM = ITEMS.register("nether_zinc_ore", () -> new BlockItem(NETHER_ZINC_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_ZINC_ORE_ITEM = ITEMS.register("end_zinc_ore", () -> new BlockItem(END_ZINC_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> ZINC_BLOCK_ITEM = ITEMS.register("zinc_block", () -> new BlockItem(ZINC_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NICKEL_ORE_ITEM = ITEMS.register("nickel_ore", () -> new BlockItem(NICKEL_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_NICKEL_ORE_ITEM = ITEMS.register("deepslate_nickel_ore", () -> new BlockItem(DEEPSLATE_NICKEL_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_NICKEL_ORE_ITEM = ITEMS.register("nether_nickel_ore", () -> new BlockItem(NETHER_NICKEL_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_NICKEL_ORE_ITEM = ITEMS.register("end_nickel_ore", () -> new BlockItem(END_NICKEL_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NICKEL_BLOCK_ITEM = ITEMS.register("nickel_block", () -> new BlockItem(NICKEL_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> LEAD_ORE_ITEM = ITEMS.register("lead_ore", () -> new BlockItem(LEAD_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_LEAD_ORE_ITEM = ITEMS.register("deepslate_lead_ore", () -> new BlockItem(DEEPSLATE_LEAD_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_LEAD_ORE_ITEM = ITEMS.register("nether_lead_ore", () -> new BlockItem(NETHER_LEAD_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_LEAD_ORE_ITEM = ITEMS.register("end_lead_ore", () -> new BlockItem(END_LEAD_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> LEAD_BLOCK_ITEM = ITEMS.register("lead_block", () -> new BlockItem(LEAD_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> OSMIUM_ORE_ITEM = ITEMS.register("osmium_ore", () -> new BlockItem(OSMIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_OSMIUM_ORE_ITEM = ITEMS.register("deepslate_osmium_ore", () -> new BlockItem(DEEPSLATE_OSMIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_OSMIUM_ORE_ITEM = ITEMS.register("nether_osmium_ore", () -> new BlockItem(NETHER_OSMIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_OSMIUM_ORE_ITEM = ITEMS.register("end_osmium_ore", () -> new BlockItem(END_OSMIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> OSMIUM_BLOCK_ITEM = ITEMS.register("osmium_block", () -> new BlockItem(OSMIUM_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> PLATINUM_ORE_ITEM = ITEMS.register("platinum_ore", () -> new BlockItem(PLATINUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_PLATINUM_ORE_ITEM = ITEMS.register("deepslate_platinum_ore", () -> new BlockItem(DEEPSLATE_PLATINUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_PLATINUM_ORE_ITEM = ITEMS.register("nether_platinum_ore", () -> new BlockItem(NETHER_PLATINUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_PLATINUM_ORE_ITEM = ITEMS.register("end_platinum_ore", () -> new BlockItem(END_PLATINUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> PLATINUM_BLOCK_ITEM = ITEMS.register("platinum_block", () -> new BlockItem(PLATINUM_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> SILVER_ORE_ITEM = ITEMS.register("silver_ore", () -> new BlockItem(SILVER_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_SILVER_ORE_ITEM = ITEMS.register("deepslate_silver_ore", () -> new BlockItem(DEEPSLATE_SILVER_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_SILVER_ORE_ITEM = ITEMS.register("nether_silver_ore", () -> new BlockItem(NETHER_SILVER_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_SILVER_ORE_ITEM = ITEMS.register("end_silver_ore", () -> new BlockItem(END_SILVER_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> SILVER_BLOCK_ITEM = ITEMS.register("silver_block", () -> new BlockItem(SILVER_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> URANIUM_ORE_ITEM = ITEMS.register("uranium_ore", () -> new BlockItem(URANIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> DEEPSLATE_URANIUM_ORE_ITEM = ITEMS.register("deepslate_uranium_ore", () -> new BlockItem(DEEPSLATE_URANIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> NETHER_URANIUM_ORE_ITEM = ITEMS.register("nether_uranium_ore", () -> new BlockItem(NETHER_URANIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> END_URANIUM_ORE_ITEM = ITEMS.register("end_uranium_ore", () -> new BlockItem(END_URANIUM_ORE.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<Item> URANIUM_BLOCK_ITEM = ITEMS.register("uranium_block", () -> new BlockItem(URANIUM_BLOCK.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));

    public static final RegistryObject<CoalPowerGenerator> COAL_POWER_GENERATOR = BLOCKS.register("coal_power_generator", CoalPowerGenerator::new);
    public static final RegistryObject<Item> COAL_POWER_GENERATOR_ITEM = ITEMS.register("coal_power_generator", () -> new BlockItem(COAL_POWER_GENERATOR.get(), new Item.Properties().tab(ModSetup.CLASSIC_TAB)));
    public static final RegistryObject<BlockEntityType<CoalPowerGeneratorBlockEntity>> COAL_POWER_GENERATOR_BLOCK_ENTITY = BLOCK_ENTITIES.register("coal_power_generator", () -> BlockEntityType.Builder.of(CoalPowerGeneratorBlockEntity::new, COAL_POWER_GENERATOR.get()).build(null));
    public static final RegistryObject<MenuType<CoalPowerGeneratorContainer>> COAL_POWER_GENERATOR_CONTAINER = CONTAINERS.register("coal_power_generator_container", () -> IForgeMenuType.create((windowId, inv, data) -> new CoalPowerGeneratorContainer(windowId, data.readBlockPos(), inv, inv.player)));

    public static final RegistryObject<TitaniumIngot> TITANIUM_INGOT = ITEMS.register("titanium_ingot", TitaniumIngot::new);
    public static final RegistryObject<TitaniumNugget> TITANIUM_NUGGET = ITEMS.register("titanium_nugget", TitaniumNugget::new);
    public static final RegistryObject<TitaniumStick> TITANIUM_STICK = ITEMS.register("titanium_stick", TitaniumStick::new);
    public static final RegistryObject<RawTitanium> RAW_TITANIUM = ITEMS.register("raw_titanium", RawTitanium::new);
    public static final RegistryObject<ChlorophyteIngot> CHLOROPHYTE_INGOT = ITEMS.register("chlorophyte_ingot", ChlorophyteIngot::new);
    public static final RegistryObject<ChlorophyteNugget> CHLOROPHYTE_NUGGET = ITEMS.register("chlorophyte_nugget", ChlorophyteNugget::new);
    public static final RegistryObject<ChlorophyteStick> CHLOROPHYTE_STICK = ITEMS.register("chlorophyte_stick", ChlorophyteStick::new);
    public static final RegistryObject<RawChlorophyte> RAW_CHLOROPHYTE = ITEMS.register("raw_chlorophyte", RawChlorophyte::new);
    public static final RegistryObject<BronzeIngot> BRONZE_INGOT = ITEMS.register("bronze_ingot", BronzeIngot::new);
    public static final RegistryObject<BronzeNugget> BRONZE_NUGGET = ITEMS.register("bronze_nugget", BronzeNugget::new);
    public static final RegistryObject<BronzeStick> BRONZE_STICK = ITEMS.register("bronze_stick", BronzeStick::new);
    public static final RegistryObject<RawBronze> RAW_BRONZE = ITEMS.register("raw_bronze", RawBronze::new);
    public static final RegistryObject<TinIngot> TIN_INGOT = ITEMS.register("tin_ingot", TinIngot::new);
    public static final RegistryObject<TinNugget> TIN_NUGGET = ITEMS.register("tin_nugget", TinNugget::new);
    public static final RegistryObject<TinStick> TIN_STICK = ITEMS.register("tin_stick", TinStick::new);
    public static final RegistryObject<RawTin> RAW_TIN = ITEMS.register("raw_tin", RawTin::new);
    public static final RegistryObject<ZincIngot> ZINC_INGOT = ITEMS.register("zinc_ingot", ZincIngot::new);
    public static final RegistryObject<ZincNugget> ZINC_NUGGET = ITEMS.register("zinc_nugget", ZincNugget::new);
    public static final RegistryObject<ZincStick> ZINC_STICK = ITEMS.register("zinc_stick", ZincStick::new);
    public static final RegistryObject<RawZinc> RAW_ZINC = ITEMS.register("raw_zinc", RawZinc::new);
    public static final RegistryObject<NickelIngot> NICKEL_INGOT = ITEMS.register("nickel_ingot", NickelIngot::new);
    public static final RegistryObject<NickelNugget> NICKEL_NUGGET = ITEMS.register("nickel_nugget", NickelNugget::new);
    public static final RegistryObject<NickelStick> NICKEL_STICK = ITEMS.register("nickel_stick", NickelStick::new);
    public static final RegistryObject<RawNickel> RAW_NICKEL = ITEMS.register("raw_nickel", RawNickel::new);
    public static final RegistryObject<LeadIngot> LEAD_INGOT = ITEMS.register("lead_ingot", LeadIngot::new);
    public static final RegistryObject<LeadNugget> LEAD_NUGGET = ITEMS.register("lead_nugget", LeadNugget::new);
    public static final RegistryObject<LeadStick> LEAD_STICK = ITEMS.register("lead_stick", LeadStick::new);
    public static final RegistryObject<RawLead> RAW_LEAD = ITEMS.register("raw_lead", RawLead::new);
    public static final RegistryObject<OsmiumIngot> OSMIUM_INGOT = ITEMS.register("osmium_ingot", OsmiumIngot::new);
    public static final RegistryObject<OsmiumNugget> OSMIUM_NUGGET = ITEMS.register("osmium_nugget", OsmiumNugget::new);
    public static final RegistryObject<OsmiumStick> OSMIUM_STICK = ITEMS.register("osmium_stick", OsmiumStick::new);
    public static final RegistryObject<RawOsmium> RAW_OSMIUM = ITEMS.register("raw_osmium", RawOsmium::new);
    public static final RegistryObject<PlatinumIngot> PLATINUM_INGOT = ITEMS.register("platinum_ingot", PlatinumIngot::new);
    public static final RegistryObject<PlatinumNugget> PLATINUM_NUGGET = ITEMS.register("platinum_nugget", PlatinumNugget::new);
    public static final RegistryObject<PlatinumStick> PLATINUM_STICK = ITEMS.register("platinum_stick", PlatinumStick::new);
    public static final RegistryObject<RawPlatinum> RAW_PLATINUM = ITEMS.register("raw_platinum", RawPlatinum::new);
    public static final RegistryObject<SilverIngot> SILVER_INGOT = ITEMS.register("silver_ingot", SilverIngot::new);
    public static final RegistryObject<SilverNugget> SILVER_NUGGET = ITEMS.register("silver_nugget", SilverNugget::new);
    public static final RegistryObject<SilverStick> SILVER_STICK = ITEMS.register("silver_stick", SilverStick::new);
    public static final RegistryObject<RawSilver> RAW_SILVER = ITEMS.register("raw_silver", RawSilver::new);
    public static final RegistryObject<UraniumIngot> URANIUM_INGOT = ITEMS.register("uranium_ingot", UraniumIngot::new);
    public static final RegistryObject<UraniumNugget> URANIUM_NUGGET = ITEMS.register("uranium_nugget", UraniumNugget::new);
    public static final RegistryObject<UraniumStick> URANIUM_STICK = ITEMS.register("uranium_stick", UraniumStick::new);
    public static final RegistryObject<RawUranium> RAW_URANIUM = ITEMS.register("raw_uranium", RawUranium::new);
    public static final RegistryObject<TitaniumElectroPickaxe> TITANIUM_ELECTRO_PICKAXE = ITEMS.register("titanium_electro_pickaxe", TitaniumElectroPickaxe::new);
    public static final RegistryObject<TitaniumElectroHammer> TITANIUM_ELECTRO_HAMMER = ITEMS.register("titanium_electro_hammer", TitaniumElectroHammer::new);
    public static final RegistryObject<TitaniumElectroSword> TITANIUM_ELECTRO_SWORD = ITEMS.register("titanium_electro_sword", TitaniumElectroSword::new);
    public static final RegistryObject<TitaniumElectroAxe> TITANIUM_ELECTRO_AXE = ITEMS.register("titanium_electro_axe", TitaniumElectroAxe::new);
    public static final RegistryObject<TitaniumElectroShovel> TITANIUM_ELECTRO_SHOVEL = ITEMS.register("titanium_electro_shovel", TitaniumElectroShovel::new);
}
